<?php

namespace SowkaBundle\Repository;

use SowkaBundle\Entity\Category;
use SowkaBundle\Entity\Exercise;

/**
 * ExerciseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllInCategory(Category $category)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('e')
            ->from('SowkaBundle:Exercise', 'e')
            ->where('e.category = :category')
            ->setParameter('category', $category)
            ->getQuery()
            ->getResult();
    }
}
