<?php

namespace SowkaBundle\Repository;

/**
 * RewardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RewardRepository extends \Doctrine\ORM\EntityRepository
{
}
